*** Commands to reproduce the experiments over the BIKE KEM.
*** Author: Víctor García Valero <vicgarval@upv.es>

***
*** LOADING MODULES
***

load ./bike.maude

***
*** SEARCH
***

*** Agreement search on init1
search init1 =>! { CONT4:Content } < (Alice[sharedKey(Bob,K1:SKey) ; KS1]CONT1) (Bob[sharedKey(Alice,K1:SKey) ; KS2]CONT2) PS >net(MSGS) .
*** MITM Attack search on init1
search init1 =>! { CONT4:Content } < (ID1[sharedKey(ID3,K1:SKey) ; KS1]CONT1) (ID2[sharedKey(ID1,K1:SKey) ; sharedKey(ID3,K2:SKey) ; KS2]CONT2) (ID3[sharedKey(ID1,K2:SKey) ; KS3]CONT3) >net(MSGS) .

*** Agreement search on init2
search init2 =>! { CONT4:Content } < (Alice[sharedKey(Bob,K1:SKey) ; KS1]CONT1) (Bob[sharedKey(Alice,K1:SKey) ; KS2]CONT2) PS >net(MSGS) .
*** MITM Attack search on init2
search [1] init2 =>! { CONT4:Content } < (ID1[sharedKey(ID3,K1:SKey) ; KS1]CONT1) (ID2[sharedKey(ID1,K1:SKey) ; sharedKey(ID3,K2:SKey) ; KS2]CONT2) (ID3[sharedKey(ID1,K2:SKey) ; KS3]CONT3) >net(MSGS) .

*** Identity Attack search
search init1 =>! {CONT4:Content} < (Eve[sharedKey(Bob,K1:SKey) ; KS1]CONT1) (Bob[sharedKey(Alice,K1:SKey) ; KS2]CONT2) PS >net(MSGS) .
search init2 =>! {CONT4:Content} < (Eve[sharedKey(Bob,K1:SKey) ; KS1]CONT1) (Bob[sharedKey(Alice,K1:SKey) ; KS2]CONT2) PS >net(MSGS) .

***
*** MODEL CHECKING
***

load model-checker.maude
load ./bike-PREDS.maude
load ./bike-CHECK.maude

*** KEY SHARING
red modelCheck(init1, [](wantsToShareKey(Alice,Bob) -> <> sharedAKeyWith(Alice,Bob))) .
red modelCheck(init2, [](wantsToShareKey(Alice,Bob) -> <> sharedAKeyWith(Alice,Bob))) .

*** FAIRNESS
red modelCheck(init1, []<> (wantsToShareKey(Alice,Bob) -> <> sharedAKeyWith(Alice,Bob))) .
red modelCheck(init2, []<> (wantsToShareKey(Alice,Bob) -> <> sharedAKeyWith(Alice,Bob))) .

*** SECRECY
red modelCheck(init1, ([] ~ stolenSharedKey(Alice,Eve))) .
red modelCheck(init1, ([] ~ stolenSharedKey(Bob,Eve))) .
red modelCheck(init2, ([] ~ stolenSharedKey(Alice,Eve))) .
red modelCheck(init2, ([] ~ stolenSharedKey(Bob,Eve))) .